### ISSUE TITLE
出力されたコードの下にプレビューを表示出来るように

### ISSUE THREAD

**Issue by muhi111** [Teamsasa/readme-generator#21]

**Comment by muhi111** [comment]
feat/previewに途中経過あり。titleで出力したh1タグがbodyと同じような出力になっちゃう、誰か助けてくれてもいいよ。

**Comment by yamamoto99** [comment]
style追加してh1のfont-sizeが大きくなるようにしたよ
tailwindで実装できないか軽く調べたけど、パッてできなさそうだから諦めたー

**Comment by muhi111** [comment]
あまりにも神
